name: build-test-deploy
on: 
  pull_request:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build node.js application
        run: |
          npm install
          npm run build 
